on: push
name: Consumer Hello Github Packages
jobs:
  test:
    name: Test running correctly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set Node.js 10.x
        uses: actions/node-version@master
        with:
          version: 10.x

      - name: Install dependencies
        run: npm install --registry https://npm.pkg.github.com
        
      - name: Running test using @guilouro/hello-github-packages
        run: npm test
